disabled_rules: # rule identifiers turned on by default to exclude from running
- computed_accessors_order
- cyclomatic_complexity
- vertical_parameter_alignment
- line_length
- trailing_whitespace
opt_in_rules: # 启用指定的规则
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - empty_count
  - empty_collection_literal
  - empty_string
  - fallthrough
  - file_name_no_space
  - force_unwrapping
  - function_default_parameter_at_end
  - legacy_multiple
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - redundant_type_annotation
  - trailing_closure
  - unused_import
included: # 执行 linting 时包含的路径。
  # - Pods/boss-config-ios
  # - Pods/boss-basic-common-ios
  # - Pods/boss-push-ios
  # - Pods/boss-common-ios
  # - Pods/boss-net-ios
  # - Pods/boss-login-ios
  # - Pods/boss-camera-ios
  # - Pods/boss-model-protocol-ios
  # - Pods/boss-collection-ios
  # - Pods/boss-message-ios
  - ~/soft/develop/QH/qh-net-ios/
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods
# 函数参数最多18个
function_parameter_count:
- 18
